// Autogenerated
#include <stdint.h>

static const unsigned imgButtonsWidth = 5;
static const unsigned imgButtonsHeight = 1;
static const unsigned imgButtonsSize = imgButtonsWidth + (imgButtonsHeight << 8);
extern uint8_t imgButtons[6][10];

static const unsigned imgHiWidth = 3;
static const unsigned imgHiHeight = 3;
static const unsigned imgHiSize = imgHiWidth + (imgHiHeight << 8);
extern uint8_t imgHi[12][18];

static const unsigned imgBallsWidth = 3;
static const unsigned imgBallsHeight = 3;
static const unsigned imgBallsSize = imgBallsWidth + (imgBallsHeight << 8);
extern uint8_t imgBalls[104][18];

static const unsigned imgScreenWidth = 64;
static const unsigned imgScreenHeight = 27;
static const unsigned imgScreenSize = imgScreenWidth + (imgScreenHeight << 8);
extern uint8_t imgScreen[449];

static const unsigned imgKingLoseWidth = 11;
static const unsigned imgKingLoseHeight = 10;
static const unsigned imgKingLoseSize = imgKingLoseWidth + (imgKingLoseHeight << 8);
extern uint8_t imgKingLose[220];

static const unsigned imgPlayerWidth = 13;
static const unsigned imgPlayerHeight = 11;
static const unsigned imgPlayerSize = imgPlayerWidth + (imgPlayerHeight << 8);
extern uint8_t imgPlayer[286];

static const unsigned imgTitleWidth = 64;
static const unsigned imgTitleHeight = 25;
static const unsigned imgTitleSize = imgTitleWidth + (imgTitleHeight << 8);
extern uint8_t imgTitle[923];

static const unsigned imgPlayerDWidth = 13;
static const unsigned imgPlayerDHeight = 1;
static const unsigned imgPlayerDSize = imgPlayerDWidth + (imgPlayerDHeight << 8);
extern uint8_t imgPlayerD[26];

static const unsigned imgPlayerWinWidth = 4;
static const unsigned imgPlayerWinHeight = 3;
static const unsigned imgPlayerWinSize = imgPlayerWinWidth + (imgPlayerWinHeight << 8);
extern uint8_t imgPlayerWin[24];
