// Autogenerated
#include <stdint.h>

static const unsigned imgIntroWidth = 48;
static const unsigned imgIntroHeight = 256;
static const unsigned imgIntroSize = imgIntroWidth + (imgIntroHeight << 8);
extern uint8_t imgIntro[395];

static const unsigned imgCellWidth = 3;
static const unsigned imgCellHeight = 24;
static const unsigned imgCellSize = imgCellWidth + (imgCellHeight << 8);
extern uint8_t imgCell[30][144];

static const unsigned imgGameWidth = 48;
static const unsigned imgGameHeight = 256;
static const unsigned imgGameSize = imgGameWidth + (imgGameHeight << 8);
extern uint8_t imgGame[485];
