#!/bin/bash
platform=$(uname -o)
EXT=
ASM=
if [ "$platform" == "Darwin" ]; then
    EXT=.macos
    ASM=-A../../include/sjasmplus.macos
fi
../../c8080$EXT $ASM -DARCH_MICRO80_COLOR game2048.c -o game2048.micro80.com

if [ -e  /home/alemorf/a/work/micro80_emulator/test.com ]
then
    cp game2048.micro80.com /home/alemorf/a/work/micro80_emulator/test.com
    echo Make /home/alemorf/a/work/micro80_emulator/test.com
    cd /home/alemorf/a/work/micro80_emulator && make
fi

