#!/bin/bash
platform=$(uname -o)
EXT=
ASM=
if [ "$platform" == "Darwin" ]; then
    EXT=.macos
    ASM=-A../../include/sjasmplus.macos
fi
../../c8080$EXT $ASM -DARCH_MICRO80_COLOR game2048.c -o game2048.micro80.com