#!/bin/bash
../../c8080 -DARCH_MICRO80_COLOR game2048.c -o game2048.micro80.com

if [ -e  /home/alemorf/a/work/micro80_emulator/test.com ]
then
    cp game2048.micro80.com /home/alemorf/a/work/micro80_emulator/test.com
    echo Make /home/alemorf/a/work/micro80_emulator/test.com
    cd /home/alemorf/a/work/micro80_emulator && make
fi

