// Autogenerated
#include <stdint.h>

static const unsigned imgScreenWidth = 48;
static const unsigned imgScreenHeight = 256;
static const unsigned imgScreenSize = imgScreenWidth + (imgScreenHeight << 8);
extern uint8_t imgScreen[1262];

static const unsigned imgPlayerWidth = 5;
static const unsigned imgPlayerHeight = 50;
static const unsigned imgPlayerSize = imgPlayerWidth + (imgPlayerHeight << 8);
extern uint8_t imgPlayer[500];

static const unsigned imgPlayerDWidth = 5;
static const unsigned imgPlayerDHeight = 4;
static const unsigned imgPlayerDSize = imgPlayerDWidth + (imgPlayerDHeight << 8);
extern uint8_t imgPlayerD[40];

static const unsigned imgTitleWidth = 48;
static const unsigned imgTitleHeight = 256;
static const unsigned imgTitleSize = imgTitleWidth + (imgTitleHeight << 8);
extern uint8_t imgTitle[3532];

static const unsigned imgBallsWidth = 2;
static const unsigned imgBallsHeight = 16;
static const unsigned imgBallsSize = imgBallsWidth + (imgBallsHeight << 8);
extern uint8_t imgBalls[104][64];

static const unsigned imgKingLoseWidth = 6;
static const unsigned imgKingLoseHeight = 62;
static const unsigned imgKingLoseSize = imgKingLoseWidth + (imgKingLoseHeight << 8);
extern uint8_t imgKingLose[744];

static const unsigned imgButtonsWidth = 4;
static const unsigned imgButtonsHeight = 8;
static const unsigned imgButtonsSize = imgButtonsWidth + (imgButtonsHeight << 8);
extern uint8_t imgButtons[6][64];

static const unsigned imgPlayerWinWidth = 2;
static const unsigned imgPlayerWinHeight = 16;
static const unsigned imgPlayerWinSize = imgPlayerWinWidth + (imgPlayerWinHeight << 8);
extern uint8_t imgPlayerWin[64];

static const unsigned imgHiWidth = 3;
static const unsigned imgHiHeight = 20;
static const unsigned imgHiSize = imgHiWidth + (imgHiHeight << 8);
extern uint8_t imgHi[3][120];

static const unsigned imgKingWidth = 6;
static const unsigned imgKingHeight = 126;
static const unsigned imgKingSize = imgKingWidth + (imgKingHeight << 8);
extern uint8_t imgKing[1512];
